# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_remove_hexdata_machine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModelConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VariableConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='datamodelconfig',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.VariableConfig'),
        ),
        migrations.AddField(
            model_name='datamodelconfig',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
