# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-10 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20171010_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableconfig',
            name='name',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
