# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('production', 'production'), ('marketing', 'marketing')], max_length=155),
        ),
    ]
