# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170111_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('worker', 'worker')], default='admin', max_length=155),
        ),
    ]
